// Generated by swift-winrt
// swiftlint:disable all

import WindowsFoundationAssembly

public typealias CollectionChange = WindowsFoundationCollections_CollectionChange

public protocol IIterableProtocol<T>: WindowsFoundationCollections_IIterableProtocol {
}

public typealias IIterable<T> = WindowsFoundationCollections_IIterable<T>
public typealias IIterableProjection = WindowsFoundationCollections_IIterableProjection

public protocol IIteratorProtocol<T>: WindowsFoundationCollections_IIteratorProtocol {
}

public typealias IIterator<T> = WindowsFoundationCollections_IIterator<T>
public typealias IIteratorProjection = WindowsFoundationCollections_IIteratorProjection

public protocol IKeyValuePairProtocol<K, V>: WindowsFoundationCollections_IKeyValuePairProtocol {
}

public typealias IKeyValuePair<K, V> = WindowsFoundationCollections_IKeyValuePair<K, V>
public typealias IKeyValuePairProjection = WindowsFoundationCollections_IKeyValuePairProjection

public protocol IMapChangedEventArgsProtocol<K>: WindowsFoundationCollections_IMapChangedEventArgsProtocol {
}

public typealias IMapChangedEventArgs<K> = WindowsFoundationCollections_IMapChangedEventArgs<K>
public typealias IMapChangedEventArgsProjection = WindowsFoundationCollections_IMapChangedEventArgsProjection

public protocol IMapViewProtocol<K, V>: WindowsFoundationCollections_IMapViewProtocol {
}

public typealias IMapView<K, V> = WindowsFoundationCollections_IMapView<K, V>
public typealias IMapViewProjection = WindowsFoundationCollections_IMapViewProjection

public protocol IMapProtocol<K, V>: WindowsFoundationCollections_IMapProtocol {
}

public typealias IMap<K, V> = WindowsFoundationCollections_IMap<K, V>
public typealias IMapProjection = WindowsFoundationCollections_IMapProjection

public protocol IObservableMapProtocol<K, V>: WindowsFoundationCollections_IObservableMapProtocol {
}

public typealias IObservableMap<K, V> = WindowsFoundationCollections_IObservableMap<K, V>
public typealias IObservableMapProjection = WindowsFoundationCollections_IObservableMapProjection

public protocol IObservableVectorProtocol<T>: WindowsFoundationCollections_IObservableVectorProtocol {
}

public typealias IObservableVector<T> = WindowsFoundationCollections_IObservableVector<T>
public typealias IObservableVectorProjection = WindowsFoundationCollections_IObservableVectorProjection

public protocol IPropertySetProtocol: WindowsFoundationCollections_IPropertySetProtocol {
}

public typealias IPropertySet = WindowsFoundationCollections_IPropertySet
public typealias IPropertySetProjection = WindowsFoundationCollections_IPropertySetProjection

public protocol IVectorChangedEventArgsProtocol: WindowsFoundationCollections_IVectorChangedEventArgsProtocol {
}

public typealias IVectorChangedEventArgs = WindowsFoundationCollections_IVectorChangedEventArgs
public typealias IVectorChangedEventArgsProjection = WindowsFoundationCollections_IVectorChangedEventArgsProjection

public protocol IVectorViewProtocol<T>: WindowsFoundationCollections_IVectorViewProtocol {
}

public typealias IVectorView<T> = WindowsFoundationCollections_IVectorView<T>
public typealias IVectorViewProjection = WindowsFoundationCollections_IVectorViewProjection

public protocol IVectorProtocol<T>: WindowsFoundationCollections_IVectorProtocol {
}

public typealias IVector<T> = WindowsFoundationCollections_IVector<T>
public typealias IVectorProjection = WindowsFoundationCollections_IVectorProjection
public typealias MapChangedEventHandler<K, V> = WindowsFoundationCollections_MapChangedEventHandler<K, V>
public typealias MapChangedEventHandlerProjection = WindowsFoundationCollections_MapChangedEventHandlerProjection
public typealias PropertySet = WindowsFoundationCollections_PropertySet
public typealias StringMap = WindowsFoundationCollections_StringMap
public typealias ValueSet = WindowsFoundationCollections_ValueSet
public typealias VectorChangedEventHandler<T> = WindowsFoundationCollections_VectorChangedEventHandler<T>
public typealias VectorChangedEventHandlerProjection = WindowsFoundationCollections_VectorChangedEventHandlerProjection