// Generated by swift-winrt
// swiftlint:disable all

import WindowsFoundationAssembly

public typealias CollectionChange = WindowsFoundationCollections_CollectionChange

public protocol IIterableProtocol<T>: WindowsFoundationCollections_IIterableProtocol {
}

public typealias IIterable<T> = WindowsFoundationCollections_IIterable<T>

public protocol IIteratorProtocol<T>: WindowsFoundationCollections_IIteratorProtocol {
}

public typealias IIterator<T> = WindowsFoundationCollections_IIterator<T>

public protocol IKeyValuePairProtocol<K, V>: WindowsFoundationCollections_IKeyValuePairProtocol {
}

public typealias IKeyValuePair<K, V> = WindowsFoundationCollections_IKeyValuePair<K, V>

public protocol IMapChangedEventArgsProtocol<K>: WindowsFoundationCollections_IMapChangedEventArgsProtocol {
}

public typealias IMapChangedEventArgs<K> = WindowsFoundationCollections_IMapChangedEventArgs<K>

public protocol IMapViewProtocol<K, V>: WindowsFoundationCollections_IMapViewProtocol {
}

public typealias IMapView<K, V> = WindowsFoundationCollections_IMapView<K, V>

public protocol IMapProtocol<K, V>: WindowsFoundationCollections_IMapProtocol {
}

public typealias IMap<K, V> = WindowsFoundationCollections_IMap<K, V>

public protocol IObservableMapProtocol<K, V>: WindowsFoundationCollections_IObservableMapProtocol {
}

public typealias IObservableMap<K, V> = WindowsFoundationCollections_IObservableMap<K, V>

public protocol IObservableVectorProtocol<T>: WindowsFoundationCollections_IObservableVectorProtocol {
}

public typealias IObservableVector<T> = WindowsFoundationCollections_IObservableVector<T>

public protocol IPropertySetProtocol: WindowsFoundationCollections_IPropertySetProtocol {
}

public typealias IPropertySet = WindowsFoundationCollections_IPropertySet
public typealias IPropertySetProjection = WindowsFoundationCollections_IPropertySetProjection

public protocol IVectorChangedEventArgsProtocol: WindowsFoundationCollections_IVectorChangedEventArgsProtocol {
}

public typealias IVectorChangedEventArgs = WindowsFoundationCollections_IVectorChangedEventArgs
public typealias IVectorChangedEventArgsProjection = WindowsFoundationCollections_IVectorChangedEventArgsProjection

public protocol IVectorViewProtocol<T>: WindowsFoundationCollections_IVectorViewProtocol {
}

public typealias IVectorView<T> = WindowsFoundationCollections_IVectorView<T>

public protocol IVectorProtocol<T>: WindowsFoundationCollections_IVectorProtocol {
}

public typealias IVector<T> = WindowsFoundationCollections_IVector<T>
public typealias MapChangedEventHandler<K, V> = WindowsFoundationCollections_MapChangedEventHandler<K, V>
public typealias PropertySet = WindowsFoundationCollections_PropertySet
public typealias StringMap = WindowsFoundationCollections_StringMap
public typealias ValueSet = WindowsFoundationCollections_ValueSet
public typealias VectorChangedEventHandler<T> = WindowsFoundationCollections_VectorChangedEventHandler<T>