// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

/// Represents a method that handles the completed event of an asynchronous action.
/// - Parameter asyncInfo: The asynchronous action.
/// - Parameter asyncStatus: One of the enumeration values.
public typealias WindowsFoundation_AsyncActionCompletedHandler = (WindowsFoundation_IAsyncAction?, WindowsFoundation_AsyncStatus) throws -> Swift.Void

public final class WindowsFoundation_AsyncActionCompletedHandlerProjection: WinRTDelegateProjectionBase<WindowsFoundation_AsyncActionCompletedHandlerProjection>, COMTwoWayProjection {
    public typealias SwiftObject = WindowsFoundation_AsyncActionCompletedHandler
    public typealias COMInterface = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIAsyncActionCompletedHandler
    public typealias COMVirtualTable = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIAsyncActionCompletedHandlerVtbl

    public static let iid = IID(0xA4ED5C81, 0x76C9, 0x40BD, 0x8BE6, 0xB1D90FB20AE7)

    public override var swiftObject: SwiftObject {
        invoke
    }

    public func invoke(_ asyncInfo: WindowsFoundation_IAsyncAction?, _ asyncStatus: WindowsFoundation_AsyncStatus) throws {
        var asyncInfo = try WindowsFoundation_IAsyncActionProjection.toABI(asyncInfo)
        defer { WindowsFoundation_IAsyncActionProjection.release(&asyncInfo) }
        let asyncStatus = WindowsFoundation_AsyncStatus.toABI(asyncStatus)
        try HResult.throwIfFailed(comPointer.pointee.lpVtbl.pointee.Invoke(comPointer, asyncInfo, asyncStatus))
    }

    public static var virtualTablePointer: COMVirtualTablePointer {
        fatalError("Not implemented: \(#function)")
    }
}