// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

/// Represents a method that handles progress update events of an asynchronous operation that provides progress updates.
/// - Parameter progressInfo: The progress information.
/// - Parameter asyncInfo: The asynchronous operation.
public typealias WindowsFoundation_AsyncOperationProgressHandler<TResult, TProgress> = (WindowsFoundation_IAsyncOperationWithProgress<TResult, TProgress>?, TProgress) throws -> Swift.Void

public enum WindowsFoundation_AsyncOperationProgressHandlerProjection {
}