// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

/// Represents an instant in time, typically expressed as a date and time of day.
public struct WindowsFoundation_DateTime: Hashable, Codable {
    /// A 64-bit signed integer that represents a point in time as the number of 100-nanosecond intervals prior to or after midnight on January 1, 1601 (according to the Gregorian Calendar).
    public var universalTime: Swift.Int64

    public init() {
        self.universalTime = 0
    }

    public init(universalTime: Swift.Int64) {
        self.universalTime = universalTime
    }
}

extension WindowsFoundation_DateTime: COM.ABIInertProjection {
    public typealias SwiftValue = Self
    public typealias ABIValue = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CDateTime

    public static var abiDefaultValue: CWindowsFoundation.__x_ABI_CWindows_CFoundation_CDateTime {
        .init()
    }

    public static func toSwift(_ value: CWindowsFoundation.__x_ABI_CWindows_CFoundation_CDateTime) -> Self {
        .init(universalTime: value.UniversalTime)
    }

    public static func toABI(_ value: Self) -> CWindowsFoundation.__x_ABI_CWindows_CFoundation_CDateTime {
        .init(UniversalTime: value.universalTime)
    }
}