// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

/// Represents a method that handles general events.
/// - Parameter args: The event data.
/// - Parameter sender: The event source.
public typealias WindowsFoundation_EventHandler<T> = (WindowsRuntime.IInspectable?, T) throws -> Swift.Void

public enum WindowsFoundation_EventHandlerProjection {
}