// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

/// Defines a method to release allocated resources.
public protocol WindowsFoundation_IClosableProtocol: IInspectableProtocol {
    /// Releases system resources that are exposed by a Windows Runtime object.
    func close() throws
}

/// Defines a method to release allocated resources.
public typealias WindowsFoundation_IClosable = any WindowsFoundation_IClosableProtocol

public final class WindowsFoundation_IClosableProjection: WinRTProjectionBase<WindowsFoundation_IClosableProjection>, WinRTProjection, WindowsFoundation_IClosableProtocol {
    public typealias SwiftObject = WindowsFoundation_IClosable
    public typealias COMInterface = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIClosable
    public typealias COMVirtualTable = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIClosableVtbl

    public static let iid = IID(0x30D5A829, 0x7FA4, 0x4026, 0x83BB, 0xD75BAE4EA99E)
    public static let runtimeClassName = "Windows.Foundation.IClosable"

    // Windows.Foundation.IClosable
    public func close() throws {
        try HResult.throwIfFailed(comPointer.pointee.lpVtbl.pointee.Close(comPointer))
    }
}