// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

/// Enables arbitrary enumerations, structures, and delegate types to be used as property values.
public protocol WindowsFoundation_IReferenceProtocol<T>: WindowsFoundation_IPropertyValueProtocol {
    associatedtype T

    /// Gets the type that is represented as an IPropertyValue.
    /// - Returns: The type.
    var value: T { get throws }
}

/// Enables arbitrary enumerations, structures, and delegate types to be used as property values.
public typealias WindowsFoundation_IReference<T> = any WindowsFoundation_IReferenceProtocol<T>

public enum WindowsFoundation_IReferenceProjection {
}