// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

/// Represents x- and y-coordinate values that define a point in a two-dimensional plane.
public struct WindowsFoundation_Point: Hashable, Codable {
    /// The horizontal position of the point.
    public var x: Swift.Float

    /// The vertical position of the point.
    public var y: Swift.Float

    public init() {
        self.x = 0
        self.y = 0
    }

    public init(x: Swift.Float, y: Swift.Float) {
        self.x = x
        self.y = y
    }
}

extension WindowsFoundation_Point: COM.ABIInertProjection {
    public typealias SwiftValue = Self
    public typealias ABIValue = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CPoint

    public static var abiDefaultValue: CWindowsFoundation.__x_ABI_CWindows_CFoundation_CPoint {
        .init()
    }

    public static func toSwift(_ value: CWindowsFoundation.__x_ABI_CWindows_CFoundation_CPoint) -> Self {
        .init(x: value.X, y: value.Y)
    }

    public static func toABI(_ value: Self) -> CWindowsFoundation.__x_ABI_CWindows_CFoundation_CPoint {
        .init(X: value.x, Y: value.y)
    }
}