// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

/// Represents a method that handles general events.
/// - Parameter args: The event data. If there is no event data, this parameter will be null.
/// - Parameter sender: The event source.
public typealias WindowsFoundation_TypedEventHandler<TSender, TResult> = (TSender, TResult) throws -> Swift.Void

public enum WindowsFoundation_TypedEventHandlerProjection {
}