// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

/// Describes the action that causes a change to a collection.
public struct WindowsFoundationCollections_CollectionChange: RawRepresentable, Hashable, Codable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    /// The collection is changed.
    public static let reset = Self(rawValue: 0)

    /// An item is added to the collection.
    public static let itemInserted = Self(rawValue: 1)

    /// An item is removed from the collection.
    public static let itemRemoved = Self(rawValue: 2)

    /// An item is changed in the collection.
    public static let itemChanged = Self(rawValue: 3)
}

extension WindowsFoundationCollections_CollectionChange: WindowsRuntime.EnumProjection {
    public typealias CEnum = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CCollections_CCollectionChange
}