// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

extension WindowsFoundationCollections_IKeyValuePairProjection {
    public final class String_String: WinRTProjectionBase<String_String>, WinRTProjection, WindowsFoundationCollections_IKeyValuePairProtocol {
        public typealias SwiftObject = WindowsFoundationCollections_IKeyValuePair<Swift.String, Swift.String>
        public typealias COMInterface = CWindowsFoundation.__FIKeyValuePair_2_HSTRING_HSTRING
        public typealias COMVirtualTable = CWindowsFoundation.__FIKeyValuePair_2_HSTRING_HSTRINGVtbl

        public static let iid = IID(0x60310303, 0x49C5, 0x52E6, 0xABC6, 0xA9B36ECCC716)
        public static let runtimeClassName = "Windows.Foundation.Collections.IKeyValuePair`2<String, String>"

        // Windows.Foundation.Collections.IKeyValuePair`2<String, String>
        public var key: Swift.String {
            get throws {
                var _result: CWindowsFoundation.HSTRING? = nil
                try HResult.throwIfFailed(comPointer.pointee.lpVtbl.pointee.get_Key(comPointer, &_result))
                return WindowsRuntime.HStringProjection.toSwift(consuming: &_result)
            }
        }

        public var value: Swift.String {
            get throws {
                var _result: CWindowsFoundation.HSTRING? = nil
                try HResult.throwIfFailed(comPointer.pointee.lpVtbl.pointee.get_Value(comPointer, &_result))
                return WindowsRuntime.HStringProjection.toSwift(consuming: &_result)
            }
        }
    }
}