// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

/// Represents a key-value pair. This is typically used as a constraint type when you need to encapsulate two type parameters into one to satisfy the constraints of another generic interface.
public protocol WindowsFoundationCollections_IKeyValuePairProtocol<K, V>: IInspectableProtocol {
    associatedtype K
    associatedtype V

    /// Gets the key of the key-value pair.
    /// - Returns: The key.
    var key: K { get throws }

    /// Gets the value of the key-value pair.
    /// - Returns: The value.
    var value: V { get throws }
}

/// Represents a key-value pair. This is typically used as a constraint type when you need to encapsulate two type parameters into one to satisfy the constraints of another generic interface.
public typealias WindowsFoundationCollections_IKeyValuePair<K, V> = any WindowsFoundationCollections_IKeyValuePairProtocol<K, V>

public enum WindowsFoundationCollections_IKeyValuePairProjection {
}