// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

extension WindowsFoundationCollections_IMapProjection {
    public final class String_String: WinRTProjectionBase<String_String>, WinRTProjection, WindowsFoundationCollections_IMapProtocol {
        public typealias SwiftObject = WindowsFoundationCollections_IMap<Swift.String, Swift.String>
        public typealias COMInterface = CWindowsFoundation.__FIMap_2_HSTRING_HSTRING
        public typealias COMVirtualTable = CWindowsFoundation.__FIMap_2_HSTRING_HSTRINGVtbl

        public static let iid = IID(0xF6D1F700, 0x49C2, 0x52AE, 0x8154, 0x826F9908773C)
        public static let runtimeClassName = "Windows.Foundation.Collections.IMap`2<String, String>"

        public typealias T = WindowsFoundationCollections_IKeyValuePair<Swift.String, Swift.String>?

        // Windows.Foundation.Collections.IMap`2<String, String>
        public var size: Swift.UInt32 {
            get throws {
                var _result: UINT32 = 0
                try HResult.throwIfFailed(comPointer.pointee.lpVtbl.pointee.get_Size(comPointer, &_result))
                return _result
            }
        }

        public func lookup(_ key: Swift.String) throws -> Swift.String {
            var key = try WindowsRuntime.HStringProjection.toABI(key)
            defer { WindowsRuntime.HStringProjection.release(&key) }
            var _result: CWindowsFoundation.HSTRING? = nil
            try HResult.throwIfFailed(comPointer.pointee.lpVtbl.pointee.Lookup(comPointer, key, &_result))
            return WindowsRuntime.HStringProjection.toSwift(consuming: &_result)
        }

        public func hasKey(_ key: Swift.String) throws -> Swift.Bool {
            var key = try WindowsRuntime.HStringProjection.toABI(key)
            defer { WindowsRuntime.HStringProjection.release(&key) }
            var _result: boolean = 0
            try HResult.throwIfFailed(comPointer.pointee.lpVtbl.pointee.HasKey(comPointer, key, &_result))
            return COM.BooleanProjection.toSwift(_result)
        }

        public func getView() throws -> WindowsFoundationCollections_IMapView<Swift.String, Swift.String>? {
            var _result: UnsafeMutablePointer<__FIMapView_2_HSTRING_HSTRING>? = nil
            try HResult.throwIfFailed(comPointer.pointee.lpVtbl.pointee.GetView(comPointer, &_result))
            return WindowsFoundationCollections_IMapViewProjection.String_String.toSwift(consuming: &_result)
        }

        public func insert(_ key: Swift.String, _ value: Swift.String) throws -> Swift.Bool {
            var key = try WindowsRuntime.HStringProjection.toABI(key)
            defer { WindowsRuntime.HStringProjection.release(&key) }
            var value = try WindowsRuntime.HStringProjection.toABI(value)
            defer { WindowsRuntime.HStringProjection.release(&value) }
            var _result: boolean = 0
            try HResult.throwIfFailed(comPointer.pointee.lpVtbl.pointee.Insert(comPointer, key, value, &_result))
            return COM.BooleanProjection.toSwift(_result)
        }

        public func remove(_ key: Swift.String) throws {
            var key = try WindowsRuntime.HStringProjection.toABI(key)
            defer { WindowsRuntime.HStringProjection.release(&key) }
            try HResult.throwIfFailed(comPointer.pointee.lpVtbl.pointee.Remove(comPointer, key))
        }

        public func clear() throws {
            try HResult.throwIfFailed(comPointer.pointee.lpVtbl.pointee.Clear(comPointer))
        }

        // Windows.Foundation.Collections.IIterable`1<Windows.Foundation.Collections.IKeyValuePair`2<String, String>>
        private var _iiterable: UnsafeMutablePointer<__FIIterable_1___FIKeyValuePair_2_HSTRING_HSTRING>! = nil

        private func _getIIterable() throws -> UnsafeMutablePointer<__FIIterable_1___FIKeyValuePair_2_HSTRING_HSTRING> {
            let iid = IID(0xE9BDAAF0, 0xCBF6, 0x5C72, 0xBE90, 0x29CBF3A1319B)
            _iiterable = try _queryInterfacePointer(iid).cast(to: __FIIterable_1___FIKeyValuePair_2_HSTRING_HSTRING.self)
            return _iiterable
        }

        public func first() throws -> WindowsFoundationCollections_IIterator<WindowsFoundationCollections_IKeyValuePair<Swift.String, Swift.String>?>? {
            let _this = try _getIIterable()
            var _result: UnsafeMutablePointer<__FIIterator_1___FIKeyValuePair_2_HSTRING_HSTRING>? = nil
            try HResult.throwIfFailed(_this.pointee.lpVtbl.pointee.First(_this, &_result))
            return WindowsFoundationCollections_IIteratorProjection.IKeyValuePair_String_String.toSwift(consuming: &_result)
        }

        deinit {
            if let _iiterable { IUnknownPointer.release(_iiterable) }
        }
    }
}