// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

/// Represents the method that handles the changed event of an observable map.
/// - Parameter sender: The observable map that changed.
/// - Parameter @event: 
      
public typealias WindowsFoundationCollections_MapChangedEventHandler<K, V> = (WindowsFoundationCollections_IObservableMap<K, V>?, WindowsFoundationCollections_IMapChangedEventArgs<K>?) throws -> Swift.Void

public enum WindowsFoundationCollections_MapChangedEventHandlerProjection {
}