// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

/// Represents the method that handles the changed event of an observable vector.
/// - Parameter @event: 
      
/// - Parameter sender: The observable vector that changed.
public typealias WindowsFoundationCollections_VectorChangedEventHandler<T> = (WindowsFoundationCollections_IObservableVector<T>?, WindowsFoundationCollections_IVectorChangedEventArgs?) throws -> Swift.Void

public enum WindowsFoundationCollections_VectorChangedEventHandlerProjection {
}