// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

extension WindowsFoundationCollections_CollectionChange: WindowsRuntime.EnumProjection {
    public typealias CEnum = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CCollections_CCollectionChange
}

public final class WindowsFoundationCollections_IPropertySetProjection: WinRTProjectionBase<WindowsFoundationCollections_IPropertySetProjection>, WinRTProjection, WindowsFoundationCollections_IPropertySetProtocol {
    public typealias K = String
    public typealias V = WindowsRuntime.IInspectable?
    public typealias T = WindowsFoundationCollections_IKeyValuePair<String, WindowsRuntime.IInspectable?>?
    public typealias SwiftValue = WindowsFoundationCollections_IPropertySet
    public typealias CStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CCollections_CIPropertySet
    public typealias CVTableStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CCollections_CIPropertySetVtbl

    public static let iid = IID(0x8A43ED9F, 0xF4E6, 0x4421, 0xACF9, 0x1DAB2986820C)
    public static let runtimeClassName = "Windows.Foundation.Collections.IPropertySet"
}

public final class WindowsFoundationCollections_IVectorChangedEventArgsProjection: WinRTProjectionBase<WindowsFoundationCollections_IVectorChangedEventArgsProjection>, WinRTProjection, WindowsFoundationCollections_IVectorChangedEventArgsProtocol {
    public typealias SwiftValue = WindowsFoundationCollections_IVectorChangedEventArgs
    public typealias CStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CCollections_CIVectorChangedEventArgs
    public typealias CVTableStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CCollections_CIVectorChangedEventArgsVtbl

    public static let iid = IID(0x575933DF, 0x34FE, 0x4480, 0xAF15, 0x07691F3D5D9B)
    public static let runtimeClassName = "Windows.Foundation.Collections.IVectorChangedEventArgs"

    public var collectionChange: WindowsFoundationCollections_CollectionChange {
        get throws {
            try _getter(_vtable.get_CollectionChange, WindowsFoundationCollections_CollectionChange.self)
        }
    }

    public var index: UInt32 {
        get throws {
            try _getter(_vtable.get_Index)
        }
    }
}

public final class WindowsFoundationCollections_PropertySet: WinRTProjectionBase<WindowsFoundationCollections_PropertySet>, WinRTProjection {
    public typealias K = String
    public typealias V = WindowsRuntime.IInspectable?
    public typealias T = WindowsFoundationCollections_IKeyValuePair<String, WindowsRuntime.IInspectable?>?
    public typealias SwiftValue = WindowsFoundationCollections_PropertySet
    public typealias CStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CCollections_CIPropertySet
    public typealias CVTableStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CCollections_CIPropertySetVtbl

    public static let iid = IID(0x8A43ED9F, 0xF4E6, 0x4421, 0xACF9, 0x1DAB2986820C)
    public static let runtimeClassName = "Windows.Foundation.Collections.PropertySet"
}

public final class WindowsFoundationCollections_StringMap: WinRTProjectionBase<WindowsFoundationCollections_StringMap>, WinRTProjection {
    public typealias K = String
    public typealias V = String
    public typealias T = WindowsFoundationCollections_IKeyValuePair<K, V>?
    public typealias SwiftValue = WindowsFoundationCollections_StringMap
    public typealias CStruct = CWindowsFoundation.__FIMap_2_HSTRING_HSTRING
    public typealias CVTableStruct = CWindowsFoundation.__FIMap_2_HSTRING_HSTRINGVtbl

    public static let iid = IID(0x3C2925FE, 0x8519, 0x45C1, 0xAA79, 0x197B6718C1C1)
    public static let runtimeClassName = "Windows.Foundation.Collections.StringMap"

    public var size: UInt32 {
        get throws {
            try _getter(_vtable.get_Size)
        }
    }

    public func lookup(_ key: K) throws -> V {
        fatalError("Not implemented: \(#function)")
    }

    public func hasKey(_ key: K) throws -> Bool {
        fatalError("Not implemented: \(#function)")
    }

    public func getView() throws -> WindowsFoundationCollections_IMapView<K, V>? {
        fatalError("Not implemented: \(#function)")
    }

    public func insert(_ key: K, _ value: V) throws -> Bool {
        fatalError("Not implemented: \(#function)")
    }

    public func remove(_ key: K) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func clear() throws {
        try HResult.throwIfFailed(_vtable.Clear(_pointer))
    }
}

public final class WindowsFoundationCollections_ValueSet: WinRTProjectionBase<WindowsFoundationCollections_ValueSet>, WinRTProjection {
    public typealias K = String
    public typealias V = WindowsRuntime.IInspectable?
    public typealias T = WindowsFoundationCollections_IKeyValuePair<String, WindowsRuntime.IInspectable?>?
    public typealias SwiftValue = WindowsFoundationCollections_ValueSet
    public typealias CStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CCollections_CIPropertySet
    public typealias CVTableStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CCollections_CIPropertySetVtbl

    public static let iid = IID(0x8A43ED9F, 0xF4E6, 0x4421, 0xACF9, 0x1DAB2986820C)
    public static let runtimeClassName = "Windows.Foundation.Collections.ValueSet"
}