// Generated by swift-winrt
// swiftlint:disable all

import CWindowsFoundation
import WindowsRuntime
import struct Foundation.UUID

extension WindowsFoundation_AsyncStatus: WindowsRuntime.EnumProjection {
    public typealias CEnum = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CAsyncStatus
}

public final class WindowsFoundation_Deferral: WinRTProjectionBase<WindowsFoundation_Deferral>, WinRTProjection {
    public typealias SwiftValue = WindowsFoundation_Deferral
    public typealias CStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIDeferral
    public typealias CVTableStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIDeferralVtbl

    public static let iid = IID(0xD6269732, 0x3B7F, 0x46A7, 0xB40B, 0x4FDCA2A2C693)
    public static let runtimeClassName = "Windows.Foundation.Deferral"

    public func complete() throws {
        try HResult.throwIfFailed(_vtable.Complete(_pointer))
    }
}

public final class WindowsFoundation_IAsyncActionProjection: WinRTProjectionBase<WindowsFoundation_IAsyncActionProjection>, WinRTProjection, WindowsFoundation_IAsyncActionProtocol {
    public typealias SwiftValue = WindowsFoundation_IAsyncAction
    public typealias CStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIAsyncAction
    public typealias CVTableStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIAsyncActionVtbl

    public static let iid = IID(0x5A648006, 0x843A, 0x4DA9, 0x865B, 0x9D26E5DFAD7B)
    public static let runtimeClassName = "Windows.Foundation.IAsyncAction"

    public var completed: WindowsFoundation_AsyncActionCompletedHandler {
        get throws {
            fatalError("Not implemented: \(#function)")
        }
    }

    public func completed(_ newValue: WindowsFoundation_AsyncActionCompletedHandler?) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getResults() throws {
        try HResult.throwIfFailed(_vtable.GetResults(_pointer))
    }
}

public final class WindowsFoundation_IAsyncInfoProjection: WinRTProjectionBase<WindowsFoundation_IAsyncInfoProjection>, WinRTProjection, WindowsFoundation_IAsyncInfoProtocol {
    public typealias SwiftValue = WindowsFoundation_IAsyncInfo
    public typealias CStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIAsyncInfo
    public typealias CVTableStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIAsyncInfoVtbl

    public static let iid = IID(0x00000036, 0x0000, 0x0000, 0xC000, 0x000000000046)
    public static let runtimeClassName = "Windows.Foundation.IAsyncInfo"

    public var errorCode: WindowsFoundation_HResult {
        get throws {
            fatalError("Not implemented: \(#function)")
        }
    }

    public var id: UInt32 {
        get throws {
            try _getter(_vtable.get_Id)
        }
    }

    public var status: WindowsFoundation_AsyncStatus {
        get throws {
            try _getter(_vtable.get_Status, WindowsFoundation_AsyncStatus.self)
        }
    }

    public func cancel() throws {
        try HResult.throwIfFailed(_vtable.Cancel(_pointer))
    }

    public func close() throws {
        try HResult.throwIfFailed(_vtable.Close(_pointer))
    }
}

public final class WindowsFoundation_IClosableProjection: WinRTProjectionBase<WindowsFoundation_IClosableProjection>, WinRTProjection, WindowsFoundation_IClosableProtocol {
    public typealias SwiftValue = WindowsFoundation_IClosable
    public typealias CStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIClosable
    public typealias CVTableStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIClosableVtbl

    public static let iid = IID(0x30D5A829, 0x7FA4, 0x4026, 0x83BB, 0xD75BAE4EA99E)
    public static let runtimeClassName = "Windows.Foundation.IClosable"

    public func close() throws {
        try HResult.throwIfFailed(_vtable.Close(_pointer))
    }
}

internal final class WindowsFoundation_IDeferralProjection: WinRTProjectionBase<WindowsFoundation_IDeferralProjection>, WinRTProjection, WindowsFoundation_IDeferralProtocol {
    public typealias SwiftValue = WindowsFoundation_IDeferral
    public typealias CStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIDeferral
    public typealias CVTableStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIDeferralVtbl

    public static let iid = IID(0xD6269732, 0x3B7F, 0x46A7, 0xB40B, 0x4FDCA2A2C693)
    public static let runtimeClassName = "Windows.Foundation.IDeferral"

    public func complete() throws {
        try HResult.throwIfFailed(_vtable.Complete(_pointer))
    }
}

public final class WindowsFoundation_IPropertyValueProjection: WinRTProjectionBase<WindowsFoundation_IPropertyValueProjection>, WinRTProjection, WindowsFoundation_IPropertyValueProtocol {
    public typealias SwiftValue = WindowsFoundation_IPropertyValue
    public typealias CStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIPropertyValue
    public typealias CVTableStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIPropertyValueVtbl

    public static let iid = IID(0x4BD682DD, 0x7554, 0x40E9, 0x9A9B, 0x82654EDE7E62)
    public static let runtimeClassName = "Windows.Foundation.IPropertyValue"

    public var isNumericScalar: Bool {
        get throws {
            try _getter(_vtable.get_IsNumericScalar, BooleanProjection.self)
        }
    }

    public var type: WindowsFoundation_PropertyType {
        get throws {
            try _getter(_vtable.get_Type, WindowsFoundation_PropertyType.self)
        }
    }

    public func getUInt8() throws -> Int8 {
        var _result = INT8()
        try HResult.throwIfFailed(_vtable.GetUInt8(_pointer, &_result))
        return _result
    }

    public func getInt16() throws -> Int16 {
        var _result = INT16()
        try HResult.throwIfFailed(_vtable.GetInt16(_pointer, &_result))
        return _result
    }

    public func getUInt16() throws -> UInt16 {
        var _result = UINT16()
        try HResult.throwIfFailed(_vtable.GetUInt16(_pointer, &_result))
        return _result
    }

    public func getInt32() throws -> Int32 {
        var _result = INT32()
        try HResult.throwIfFailed(_vtable.GetInt32(_pointer, &_result))
        return _result
    }

    public func getUInt32() throws -> UInt32 {
        var _result = UINT32()
        try HResult.throwIfFailed(_vtable.GetUInt32(_pointer, &_result))
        return _result
    }

    public func getInt64() throws -> Int64 {
        var _result = INT64()
        try HResult.throwIfFailed(_vtable.GetInt64(_pointer, &_result))
        return _result
    }

    public func getUInt64() throws -> UInt64 {
        var _result = UINT64()
        try HResult.throwIfFailed(_vtable.GetUInt64(_pointer, &_result))
        return _result
    }

    public func getSingle() throws -> Float {
        var _result = FLOAT()
        try HResult.throwIfFailed(_vtable.GetSingle(_pointer, &_result))
        return _result
    }

    public func getDouble() throws -> Double {
        var _result = DOUBLE()
        try HResult.throwIfFailed(_vtable.GetDouble(_pointer, &_result))
        return _result
    }

    public func getChar16() throws -> UTF16.CodeUnit {
        var _result = WCHAR()
        try HResult.throwIfFailed(_vtable.GetChar16(_pointer, &_result))
        return _result
    }

    public func getBoolean() throws -> Bool {
        var _result = boolean()
        try HResult.throwIfFailed(_vtable.GetBoolean(_pointer, &_result))
        return BooleanProjection.toSwift(consuming: _result)
    }

    public func getString() throws -> String {
        var _result = HSTRING?()
        try HResult.throwIfFailed(_vtable.GetString(_pointer, &_result))
        return HStringProjection.toSwift(consuming: _result)
    }

    public func getGuid() throws -> Foundation.UUID {
        fatalError("Not implemented: \(#function)")
    }

    public func getDateTime() throws -> WindowsFoundation_DateTime {
        fatalError("Not implemented: \(#function)")
    }

    public func getTimeSpan() throws -> WindowsFoundation_TimeSpan {
        fatalError("Not implemented: \(#function)")
    }

    public func getPoint() throws -> WindowsFoundation_Point {
        fatalError("Not implemented: \(#function)")
    }

    public func getSize() throws -> WindowsFoundation_Size {
        fatalError("Not implemented: \(#function)")
    }

    public func getRect() throws -> WindowsFoundation_Rect {
        fatalError("Not implemented: \(#function)")
    }

    public func getUInt8Array(_ value: inout [Int8]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getInt16Array(_ value: inout [Int16]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getUInt16Array(_ value: inout [UInt16]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getInt32Array(_ value: inout [Int32]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getUInt32Array(_ value: inout [UInt32]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getInt64Array(_ value: inout [Int64]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getUInt64Array(_ value: inout [UInt64]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getSingleArray(_ value: inout [Float]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getDoubleArray(_ value: inout [Double]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getChar16Array(_ value: inout [UTF16.CodeUnit]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getBooleanArray(_ value: inout [Bool]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getStringArray(_ value: inout [String]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getInspectableArray(_ value: inout [WindowsRuntime.IInspectable?]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getGuidArray(_ value: inout [Foundation.UUID]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getDateTimeArray(_ value: inout [WindowsFoundation_DateTime]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getTimeSpanArray(_ value: inout [WindowsFoundation_TimeSpan]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getPointArray(_ value: inout [WindowsFoundation_Point]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getSizeArray(_ value: inout [WindowsFoundation_Size]) throws {
        fatalError("Not implemented: \(#function)")
    }

    public func getRectArray(_ value: inout [WindowsFoundation_Rect]) throws {
        fatalError("Not implemented: \(#function)")
    }
}

public final class WindowsFoundation_IStringableProjection: WinRTProjectionBase<WindowsFoundation_IStringableProjection>, WinRTProjection, WindowsFoundation_IStringableProtocol {
    public typealias SwiftValue = WindowsFoundation_IStringable
    public typealias CStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIStringable
    public typealias CVTableStruct = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CIStringableVtbl

    public static let iid = IID(0x96369F54, 0x8EB6, 0x48F0, 0xABCE, 0xC1B211E627C3)
    public static let runtimeClassName = "Windows.Foundation.IStringable"

    public func toString() throws -> String {
        var _result = HSTRING?()
        try HResult.throwIfFailed(_vtable.ToString(_pointer, &_result))
        return HStringProjection.toSwift(consuming: _result)
    }
}

extension WindowsFoundation_PropertyType: WindowsRuntime.EnumProjection {
    public typealias CEnum = CWindowsFoundation.__x_ABI_CWindows_CFoundation_CPropertyType
}

public final class WindowsFoundation_PropertyValue {
    private init() {
    }
}